;; Auto generated by cnfonts

;; <https://github.com/tumashu/cnfonts>

(use-package cnfonts
  :ensure t
  :defer 0.1
  :config
  (set-face-attribute

   'default nil

   :font (font-spec :name "-outline-Consolas-bold-italic-normal-mono-*-*-*-*-c-*-iso10646-1"

		    :weight 'normal

		    :slant 'normal

		    :size 12.5))

  (dolist (charset '(kana han symbol cjk-misc bopomofo))

    (set-fontset-font

     (frame-parameter nil 'font)

     charset

     (font-spec :name "-outline-微软雅黑-normal-normal-normal-sans-*-*-*-*-p-*-iso10646-1"

		:weight 'normal

		:slant 'normal

		:size 15.0)))
  )



(provide 'init-font)
